// Auto-generated by scripts/generate_enem_data.py.
// Source: projeto_extensionista\microdados_enem_por_escola\DADOS\MICRODADOS_ENEM_ESCOLA.csv.
// Recorte de desempenho: 2009-2015. Nao edite os agregados manualmente.

export type SubjectKey = 'cn' | 'ch' | 'lp' | 'mt' | 'redacao';

export interface YearScore { ano: number; cn: number; ch: number; lp: number; mt: number; redacao: number; }
export interface NetworkCount { rede: 'Publica' | 'Privada'; registros: number; percentual: number; }
export interface NetworkScore { area: string; publica: number; privada: number; }
export interface RegionalNetworkScore extends NetworkScore { regiao: string; }
export interface AdminCount { dependencia: string; rede: 'Publica' | 'Privada'; registros: number; }
export interface StateParticipation { uf: string; nome: string; regiao: string; registros: number; }
export interface ApprovalScorePoint { uf: string; regiao: string; rede: 'Publica' | 'Privada'; mediaGeral: number; taxaAprovacao: number; taxaPermanencia: number; taxaPermanenciaRegistros: number; registros: number; }
export interface StateScoreAverage { uf: string; regiao: string; mediaGeral: number; registros: number; }
export interface RegionScoreAverage { regiao: string; mediaGeral: number; registros: number; }
export interface StateNetworkScoreAverage extends StateScoreAverage { rede: 'Publica' | 'Privada'; }
export interface RegionNetworkScoreAverage extends RegionScoreAverage { rede: 'Publica' | 'Privada'; }
export interface FederalPrivateUrbanScore { area: string; federalUrbana: number; privadaUrbana: number; }
export interface RegionalFederalPrivateUrbanScore extends FederalPrivateUrbanScore { regiao: string; }
export interface UrbanRuralRegionScore { regiao: string; urbana: number; rural: number; registrosUrbanos: number; registrosRurais: number; }
export interface MapPoint { id: string; label: string; detail: string; longitude: number; latitude: number; value: number; tone: 'primary' | 'secondary' | 'accent'; }

export const yearScores: YearScore[] = [
  { ano: 2009, cn: 496.6, ch: 496.66, lp: 495.14, mt: 495.71, redacao: 579.91 },
  { ano: 2010, cn: 481.82, ch: 534.53, lp: 505.92, mt: 504.59, redacao: 591.03 },
  { ano: 2011, cn: 489.48, ch: 494.46, lp: 537.22, mt: 555.24, redacao: 559.45 },
  { ano: 2012, cn: 491.43, ch: 536.72, lp: 505.01, mt: 540.99, redacao: 533.04 },
  { ano: 2013, cn: 488.3, ch: 529.77, lp: 502.03, mt: 535.44, redacao: 537.9 },
  { ano: 2014, cn: 498.74, ch: 555.98, lp: 520.02, mt: 495.66, redacao: 515.4 },
  { ano: 2015, cn: 490.87, ch: 566.76, lp: 515.31, mt: 492.57, redacao: 563.77 },
];

export const networkCounts: NetworkCount[] = [
  { rede: 'Publica', registros: 66120, percentual: 63.16 },
  { rede: 'Privada', registros: 38567, percentual: 36.84 },
];

export const adminCounts: AdminCount[] = [
  { dependencia: 'Estadual', rede: 'Publica', registros: 63511 },
  { dependencia: 'Privada', rede: 'Privada', registros: 38567 },
  { dependencia: 'Municipal', rede: 'Publica', registros: 975 },
  { dependencia: 'Federal', rede: 'Publica', registros: 1634 },
];

export const stateParticipation: StateParticipation[] = [
  { uf: 'SP', nome: 'Sao Paulo', regiao: 'Sudeste', registros: 23004 },
  { uf: 'MG', nome: 'Minas Gerais', regiao: 'Sudeste', registros: 12202 },
  { uf: 'RJ', nome: 'Rio de Janeiro', regiao: 'Sudeste', registros: 8401 },
  { uf: 'RS', nome: 'Rio Grande do Sul', regiao: 'Sul', registros: 7503 },
  { uf: 'PR', nome: 'Parana', regiao: 'Sul', registros: 6393 },
  { uf: 'CE', nome: 'Ceara', regiao: 'Nordeste', registros: 4864 },
  { uf: 'BA', nome: 'Bahia', regiao: 'Nordeste', registros: 4711 },
  { uf: 'PE', nome: 'Pernambuco', regiao: 'Nordeste', registros: 4310 },
  { uf: 'SC', nome: 'Santa Catarina', regiao: 'Sul', registros: 4004 },
  { uf: 'GO', nome: 'Goias', regiao: 'Centro-oeste', registros: 3758 },
  { uf: 'ES', nome: 'Espirito Santo', regiao: 'Sudeste', registros: 2636 },
  { uf: 'MA', nome: 'Maranhao', regiao: 'Nordeste', registros: 2439 },
  { uf: 'PA', nome: 'Para', regiao: 'Norte', registros: 2331 },
  { uf: 'PI', nome: 'Piaui', regiao: 'Nordeste', registros: 2254 },
  { uf: 'PB', nome: 'Paraiba', regiao: 'Nordeste', registros: 2238 },
  { uf: 'MT', nome: 'Mato Grosso', regiao: 'Centro-oeste', registros: 1968 },
  { uf: 'MS', nome: 'Mato Grosso do Sul', regiao: 'Centro-oeste', registros: 1963 },
  { uf: 'RN', nome: 'Rio Grande do Norte', regiao: 'Nordeste', registros: 1780 },
  { uf: 'AM', nome: 'Amazonas', regiao: 'Norte', registros: 1291 },
  { uf: 'AL', nome: 'Alagoas', regiao: 'Nordeste', registros: 1240 },
  { uf: 'SE', nome: 'Sergipe', regiao: 'Nordeste', registros: 1182 },
  { uf: 'TO', nome: 'Tocantins', regiao: 'Norte', registros: 1101 },
  { uf: 'DF', nome: 'Distrito Federal', regiao: 'Centro-oeste', registros: 1090 },
  { uf: 'RO', nome: 'Rondonia', regiao: 'Norte', registros: 1060 },
  { uf: 'AC', nome: 'Acre', regiao: 'Norte', registros: 391 },
  { uf: 'AP', nome: 'Amapa', regiao: 'Norte', registros: 338 },
  { uf: 'RR', nome: 'Roraima', regiao: 'Norte', registros: 235 },
];

export const networkScores: NetworkScore[] = [
  { area: 'Ciencias da Natureza', publica: 463.96, privada: 537.12 },
  { area: 'Ciencias Humanas', publica: 505.24, privada: 577.19 },
  { area: 'Linguagens', publica: 485.15, privada: 552.48 },
  { area: 'Matematica', publica: 475.89, privada: 576.55 },
  { area: 'Redacao', publica: 523.86, privada: 613.81 },
];

export const regionalNetworkScores: RegionalNetworkScore[] = [
  { regiao: 'Norte', area: 'Ciencias da Natureza', publica: 445.93, privada: 514.46 },
  { regiao: 'Norte', area: 'Ciencias Humanas', publica: 489.1, privada: 559.42 },
  { regiao: 'Norte', area: 'Linguagens', publica: 463.22, privada: 531.65 },
  { regiao: 'Norte', area: 'Matematica', publica: 447.3, privada: 532.18 },
  { regiao: 'Norte', area: 'Redacao', publica: 504.32, privada: 603.39 },
  { regiao: 'Nordeste', area: 'Ciencias da Natureza', publica: 446.64, privada: 515.09 },
  { regiao: 'Nordeste', area: 'Ciencias Humanas', publica: 489.38, privada: 559.37 },
  { regiao: 'Nordeste', area: 'Linguagens', publica: 464.36, privada: 533.96 },
  { regiao: 'Nordeste', area: 'Matematica', publica: 451.12, privada: 541.87 },
  { regiao: 'Nordeste', area: 'Redacao', publica: 505.1, privada: 604.77 },
  { regiao: 'Centro-oeste', area: 'Ciencias da Natureza', publica: 460.68, privada: 532.25 },
  { regiao: 'Centro-oeste', area: 'Ciencias Humanas', publica: 502.41, privada: 571.34 },
  { regiao: 'Centro-oeste', area: 'Linguagens', publica: 480.61, privada: 545.43 },
  { regiao: 'Centro-oeste', area: 'Matematica', publica: 466.77, privada: 564.19 },
  { regiao: 'Centro-oeste', area: 'Redacao', publica: 506.84, privada: 607.19 },
  { regiao: 'Sudeste', area: 'Ciencias da Natureza', publica: 472.53, privada: 548.2 },
  { regiao: 'Sudeste', area: 'Ciencias Humanas', publica: 513.56, privada: 586.96 },
  { regiao: 'Sudeste', area: 'Linguagens', publica: 497.99, privada: 562.78 },
  { regiao: 'Sudeste', area: 'Matematica', publica: 490.5, privada: 595.37 },
  { regiao: 'Sudeste', area: 'Redacao', publica: 537.59, privada: 621.89 },
  { regiao: 'Sul', area: 'Ciencias da Natureza', publica: 476.24, privada: 544.05 },
  { regiao: 'Sul', area: 'Ciencias Humanas', publica: 515.32, privada: 580.57 },
  { regiao: 'Sul', area: 'Linguagens', publica: 495.04, privada: 556.88 },
  { regiao: 'Sul', area: 'Matematica', publica: 491.68, privada: 587.98 },
  { regiao: 'Sul', area: 'Redacao', publica: 533.99, privada: 605.83 },
];

export const approvalScoreScatter: ApprovalScorePoint[] = [
  { uf: 'AC', regiao: 'Norte', rede: 'Privada', mediaGeral: 549.04, taxaAprovacao: 95.42, taxaPermanencia: 71.15, taxaPermanenciaRegistros: 22, registros: 74 },
  { uf: 'AC', regiao: 'Norte', rede: 'Publica', mediaGeral: 462.77, taxaAprovacao: 81.48, taxaPermanencia: 74.83, taxaPermanenciaRegistros: 98, registros: 316 },
  { uf: 'AL', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 530.67, taxaAprovacao: 92.4, taxaPermanencia: 71.03, taxaPermanenciaRegistros: 213, registros: 635 },
  { uf: 'AL', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 471.28, taxaAprovacao: 71.65, taxaPermanencia: 77.71, taxaPermanenciaRegistros: 165, registros: 548 },
  { uf: 'AM', regiao: 'Norte', rede: 'Privada', mediaGeral: 550.18, taxaAprovacao: 92.42, taxaPermanencia: 67.68, taxaPermanenciaRegistros: 84, registros: 298 },
  { uf: 'AM', regiao: 'Norte', rede: 'Publica', mediaGeral: 466.41, taxaAprovacao: 83.6, taxaPermanencia: 74.67, taxaPermanenciaRegistros: 239, registros: 991 },
  { uf: 'AP', regiao: 'Norte', rede: 'Privada', mediaGeral: 538.68, taxaAprovacao: 96.2, taxaPermanencia: 69.17, taxaPermanenciaRegistros: 24, registros: 74 },
  { uf: 'AP', regiao: 'Norte', rede: 'Publica', mediaGeral: 465.46, taxaAprovacao: 71.74, taxaPermanencia: 74.51, taxaPermanenciaRegistros: 98, registros: 260 },
  { uf: 'BA', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 567.68, taxaAprovacao: 92.74, taxaPermanencia: 73.46, taxaPermanenciaRegistros: 586, registros: 1756 },
  { uf: 'BA', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 478.58, taxaAprovacao: 73.17, taxaPermanencia: 79.23, taxaPermanenciaRegistros: 674, registros: 2819 },
  { uf: 'CE', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 556.34, taxaAprovacao: 94.66, taxaPermanencia: 76.62, taxaPermanenciaRegistros: 474, registros: 1483 },
  { uf: 'CE', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 466.42, taxaAprovacao: 83.57, taxaPermanencia: 76.22, taxaPermanenciaRegistros: 1176, registros: 3367 },
  { uf: 'DF', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 578.89, taxaAprovacao: 92.64, taxaPermanencia: 70.82, taxaPermanenciaRegistros: 196, registros: 569 },
  { uf: 'DF', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 506.32, taxaAprovacao: 73.17, taxaPermanencia: 77.09, taxaPermanenciaRegistros: 167, registros: 519 },
  { uf: 'ES', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 572.42, taxaAprovacao: 93.99, taxaPermanencia: 73.02, taxaPermanenciaRegistros: 212, registros: 719 },
  { uf: 'ES', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 478.4, taxaAprovacao: 77.77, taxaPermanencia: 79.89, taxaPermanenciaRegistros: 575, registros: 1901 },
  { uf: 'GO', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 563.78, taxaAprovacao: 94.17, taxaPermanencia: 66.3, taxaPermanenciaRegistros: 421, registros: 1334 },
  { uf: 'GO', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 481.82, taxaAprovacao: 81.59, taxaPermanencia: 72.04, taxaPermanenciaRegistros: 790, registros: 2398 },
  { uf: 'MA', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 534.76, taxaAprovacao: 93.67, taxaPermanencia: 66.94, taxaPermanenciaRegistros: 226, registros: 746 },
  { uf: 'MA', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 461.01, taxaAprovacao: 78.72, taxaPermanencia: 76.09, taxaPermanenciaRegistros: 438, registros: 1681 },
  { uf: 'MG', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 598.59, taxaAprovacao: 93.61, taxaPermanencia: 78.98, taxaPermanenciaRegistros: 1109, registros: 3774 },
  { uf: 'MG', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 502.67, taxaAprovacao: 80.8, taxaPermanencia: 82.89, taxaPermanenciaRegistros: 2370, registros: 8380 },
  { uf: 'MS', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 567.97, taxaAprovacao: 93.6, taxaPermanencia: 62.75, taxaPermanenciaRegistros: 135, registros: 497 },
  { uf: 'MS', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 486.36, taxaAprovacao: 73.32, taxaPermanencia: 72.24, taxaPermanenciaRegistros: 420, registros: 1465 },
  { uf: 'MT', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 547.83, taxaAprovacao: 95.78, taxaPermanencia: 63.79, taxaPermanenciaRegistros: 187, registros: 568 },
  { uf: 'MT', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 474.5, taxaAprovacao: 69.63, taxaPermanencia: 76.44, taxaPermanenciaRegistros: 410, registros: 1350 },
  { uf: 'PA', regiao: 'Norte', rede: 'Privada', mediaGeral: 545.66, taxaAprovacao: 94.86, taxaPermanencia: 62.6, taxaPermanenciaRegistros: 294, registros: 857 },
  { uf: 'PA', regiao: 'Norte', rede: 'Publica', mediaGeral: 476.27, taxaAprovacao: 69.5, taxaPermanencia: 67.91, taxaPermanenciaRegistros: 365, registros: 1436 },
  { uf: 'PB', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 545.89, taxaAprovacao: 93.71, taxaPermanencia: 69.79, taxaPermanenciaRegistros: 231, registros: 689 },
  { uf: 'PB', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 473.3, taxaAprovacao: 77.01, taxaPermanencia: 78.63, taxaPermanenciaRegistros: 517, registros: 1486 },
  { uf: 'PE', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 543.71, taxaAprovacao: 93.89, taxaPermanencia: 71.66, taxaPermanenciaRegistros: 493, registros: 1718 },
  { uf: 'PE', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 483.29, taxaAprovacao: 83.7, taxaPermanencia: 80.48, taxaPermanenciaRegistros: 756, registros: 2566 },
  { uf: 'PI', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 565.92, taxaAprovacao: 92.97, taxaPermanencia: 66.74, taxaPermanenciaRegistros: 184, registros: 636 },
  { uf: 'PI', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 460.04, taxaAprovacao: 76.64, taxaPermanencia: 72.19, taxaPermanenciaRegistros: 459, registros: 1576 },
  { uf: 'PR', regiao: 'Sul', rede: 'Privada', mediaGeral: 568.23, taxaAprovacao: 95.87, taxaPermanencia: 72.02, taxaPermanenciaRegistros: 613, registros: 1929 },
  { uf: 'PR', regiao: 'Sul', rede: 'Publica', mediaGeral: 496.76, taxaAprovacao: 81.74, taxaPermanencia: 83.11, taxaPermanenciaRegistros: 1031, registros: 4437 },
  { uf: 'RJ', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 579.17, taxaAprovacao: 90.03, taxaPermanencia: 69.78, taxaPermanenciaRegistros: 1403, registros: 4071 },
  { uf: 'RJ', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 503.79, taxaAprovacao: 76.38, taxaPermanencia: 77.21, taxaPermanenciaRegistros: 1231, registros: 3883 },
  { uf: 'RN', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 547.72, taxaAprovacao: 93.25, taxaPermanencia: 74.22, taxaPermanenciaRegistros: 205, registros: 668 },
  { uf: 'RN', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 473.03, taxaAprovacao: 74.33, taxaPermanencia: 82.37, taxaPermanenciaRegistros: 328, registros: 1104 },
  { uf: 'RO', regiao: 'Norte', rede: 'Privada', mediaGeral: 546.16, taxaAprovacao: 93.75, taxaPermanencia: 70.4, taxaPermanenciaRegistros: 65, registros: 222 },
  { uf: 'RO', regiao: 'Norte', rede: 'Publica', mediaGeral: 478.49, taxaAprovacao: 76.69, taxaPermanencia: 72.54, taxaPermanenciaRegistros: 261, registros: 831 },
  { uf: 'RR', regiao: 'Norte', rede: 'Privada', mediaGeral: 550.86, taxaAprovacao: 94.4, taxaPermanencia: 76.42, taxaPermanenciaRegistros: 12, registros: 40 },
  { uf: 'RR', regiao: 'Norte', rede: 'Publica', mediaGeral: 472.34, taxaAprovacao: 79.14, taxaPermanencia: 75.71, taxaPermanenciaRegistros: 62, registros: 194 },
  { uf: 'RS', regiao: 'Sul', rede: 'Privada', mediaGeral: 579.59, taxaAprovacao: 92.35, taxaPermanencia: 81.24, taxaPermanenciaRegistros: 578, registros: 1859 },
  { uf: 'RS', regiao: 'Sul', rede: 'Publica', mediaGeral: 507.73, taxaAprovacao: 74.45, taxaPermanencia: 86.55, taxaPermanenciaRegistros: 1655, registros: 5621 },
  { uf: 'SC', regiao: 'Sul', rede: 'Privada', mediaGeral: 578.97, taxaAprovacao: 95.14, taxaPermanencia: 74.48, taxaPermanenciaRegistros: 369, registros: 1130 },
  { uf: 'SC', regiao: 'Sul', rede: 'Publica', mediaGeral: 501.14, taxaAprovacao: 83.09, taxaPermanencia: 82.11, taxaPermanenciaRegistros: 918, registros: 2822 },
  { uf: 'SE', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 548.09, taxaAprovacao: 91.89, taxaPermanencia: 71.41, taxaPermanenciaRegistros: 156, registros: 468 },
  { uf: 'SE', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 464.62, taxaAprovacao: 70.81, taxaPermanencia: 80.22, taxaPermanenciaRegistros: 228, registros: 703 },
  { uf: 'SP', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 580.67, taxaAprovacao: 95.79, taxaPermanencia: 77.16, taxaPermanenciaRegistros: 3593, registros: 10756 },
  { uf: 'SP', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 505.63, taxaAprovacao: 85.21, taxaPermanencia: 79.12, taxaPermanenciaRegistros: 2876, registros: 12158 },
  { uf: 'TO', regiao: 'Norte', rede: 'Privada', mediaGeral: 563.24, taxaAprovacao: 92.06, taxaPermanencia: 60.12, taxaPermanenciaRegistros: 56, registros: 168 },
  { uf: 'TO', regiao: 'Norte', rede: 'Publica', mediaGeral: 459.98, taxaAprovacao: 82.66, taxaPermanencia: 79.18, taxaPermanenciaRegistros: 286, registros: 927 },
];

export const stateScoreAverages: StateScoreAverage[] = [
  { uf: 'DF', regiao: 'Centro-oeste', mediaGeral: 544.21, registros: 1089 },
  { uf: 'RJ', regiao: 'Sudeste', mediaGeral: 543.29, registros: 8364 },
  { uf: 'SP', regiao: 'Sudeste', mediaGeral: 540.9, registros: 22928 },
  { uf: 'MG', regiao: 'Sudeste', mediaGeral: 532.48, registros: 12164 },
  { uf: 'RS', regiao: 'Sul', mediaGeral: 525.59, registros: 7481 },
  { uf: 'SC', regiao: 'Sul', mediaGeral: 524.04, registros: 3986 },
  { uf: 'PR', regiao: 'Sul', mediaGeral: 518.44, registros: 6372 },
  { uf: 'BA', regiao: 'Nordeste', mediaGeral: 514.07, registros: 4694 },
  { uf: 'GO', regiao: 'Centro-oeste', mediaGeral: 511.26, registros: 3745 },
  { uf: 'PE', regiao: 'Nordeste', mediaGeral: 507.54, registros: 4286 },
  { uf: 'MS', regiao: 'Centro-oeste', mediaGeral: 507.04, registros: 1962 },
  { uf: 'ES', regiao: 'Sudeste', mediaGeral: 504.32, registros: 2624 },
  { uf: 'AL', regiao: 'Nordeste', mediaGeral: 503.1, registros: 1234 },
  { uf: 'PA', regiao: 'Norte', mediaGeral: 502.91, registros: 2328 },
  { uf: 'RN', regiao: 'Nordeste', mediaGeral: 501.18, registros: 1773 },
  { uf: 'SE', regiao: 'Nordeste', mediaGeral: 498.28, registros: 1179 },
  { uf: 'MT', regiao: 'Centro-oeste', mediaGeral: 497.16, registros: 1956 },
  { uf: 'PB', regiao: 'Nordeste', mediaGeral: 497.07, registros: 2225 },
  { uf: 'CE', regiao: 'Nordeste', mediaGeral: 493.93, registros: 4853 },
  { uf: 'RO', regiao: 'Norte', mediaGeral: 492.75, registros: 1053 },
  { uf: 'PI', regiao: 'Nordeste', mediaGeral: 490.72, registros: 2238 },
  { uf: 'AM', regiao: 'Norte', mediaGeral: 485.81, registros: 1290 },
  { uf: 'RR', regiao: 'Norte', mediaGeral: 485.76, registros: 234 },
  { uf: 'MA', regiao: 'Nordeste', mediaGeral: 483.68, registros: 2427 },
  { uf: 'AP', regiao: 'Norte', mediaGeral: 482.12, registros: 336 },
  { uf: 'AC', regiao: 'Norte', mediaGeral: 479.14, registros: 390 },
  { uf: 'TO', regiao: 'Norte', mediaGeral: 475.91, registros: 1096 },
];

export const regionScoreAverages: RegionScoreAverage[] = [
  { regiao: 'Norte', mediaGeral: 490.63, registros: 6727 },
  { regiao: 'Nordeste', mediaGeral: 500.24, registros: 24909 },
  { regiao: 'Centro-oeste', mediaGeral: 511.26, registros: 8752 },
  { regiao: 'Sudeste', mediaGeral: 537.02, registros: 46080 },
  { regiao: 'Sul', mediaGeral: 522.69, registros: 17839 },
];

export const stateNetworkScoreAverages: StateNetworkScoreAverage[] = [
  { uf: 'MG', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 598.53, registros: 3781 },
  { uf: 'SP', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 580.68, registros: 10767 },
  { uf: 'RS', regiao: 'Sul', rede: 'Privada', mediaGeral: 579.59, registros: 1859 },
  { uf: 'SC', regiao: 'Sul', rede: 'Privada', mediaGeral: 579.55, registros: 1164 },
  { uf: 'DF', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 578.89, registros: 569 },
  { uf: 'RJ', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 577.5, registros: 4470 },
  { uf: 'ES', regiao: 'Sudeste', rede: 'Privada', mediaGeral: 572.35, registros: 721 },
  { uf: 'PR', regiao: 'Sul', rede: 'Privada', mediaGeral: 568.14, registros: 1935 },
  { uf: 'MS', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 567.97, registros: 497 },
  { uf: 'BA', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 567.33, registros: 1869 },
  { uf: 'PI', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 563.74, registros: 662 },
  { uf: 'GO', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 563.67, registros: 1345 },
  { uf: 'TO', regiao: 'Norte', rede: 'Privada', mediaGeral: 563.31, registros: 169 },
  { uf: 'CE', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 556.27, registros: 1486 },
  { uf: 'RR', regiao: 'Norte', rede: 'Privada', mediaGeral: 550.86, registros: 40 },
  { uf: 'AM', regiao: 'Norte', rede: 'Privada', mediaGeral: 550.08, registros: 299 },
  { uf: 'AC', regiao: 'Norte', rede: 'Privada', mediaGeral: 549.04, registros: 74 },
  { uf: 'SE', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 548.09, registros: 468 },
  { uf: 'MT', regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 547.71, registros: 601 },
  { uf: 'RN', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 547.63, registros: 669 },
  { uf: 'RO', regiao: 'Norte', rede: 'Privada', mediaGeral: 546.16, registros: 222 },
  { uf: 'PA', regiao: 'Norte', rede: 'Privada', mediaGeral: 545.81, registros: 892 },
  { uf: 'PB', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 545, registros: 736 },
  { uf: 'PE', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 543.73, registros: 1720 },
  { uf: 'AP', regiao: 'Norte', rede: 'Privada', mediaGeral: 539.1, registros: 76 },
  { uf: 'MA', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 534.76, registros: 746 },
  { uf: 'AL', regiao: 'Nordeste', rede: 'Privada', mediaGeral: 530.43, registros: 658 },
  { uf: 'RS', regiao: 'Sul', rede: 'Publica', mediaGeral: 507.74, registros: 5622 },
  { uf: 'DF', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 506.27, registros: 520 },
  { uf: 'SP', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 505.67, registros: 12161 },
  { uf: 'RJ', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 504.01, registros: 3894 },
  { uf: 'MG', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 502.69, registros: 8383 },
  { uf: 'SC', regiao: 'Sul', rede: 'Publica', mediaGeral: 501.14, registros: 2822 },
  { uf: 'PR', regiao: 'Sul', rede: 'Publica', mediaGeral: 496.76, registros: 4437 },
  { uf: 'MS', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 486.36, registros: 1465 },
  { uf: 'PE', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 483.29, registros: 2566 },
  { uf: 'GO', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 481.89, registros: 2400 },
  { uf: 'BA', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 478.83, registros: 2825 },
  { uf: 'ES', regiao: 'Sudeste', rede: 'Publica', mediaGeral: 478.54, registros: 1903 },
  { uf: 'RO', regiao: 'Norte', rede: 'Publica', mediaGeral: 478.49, registros: 831 },
  { uf: 'PA', regiao: 'Norte', rede: 'Publica', mediaGeral: 476.27, registros: 1436 },
  { uf: 'MT', regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 474.74, registros: 1355 },
  { uf: 'PB', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 473.38, registros: 1489 },
  { uf: 'RN', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 473.03, registros: 1104 },
  { uf: 'RR', regiao: 'Norte', rede: 'Publica', mediaGeral: 472.34, registros: 194 },
  { uf: 'AL', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 471.87, registros: 576 },
  { uf: 'CE', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 466.42, registros: 3367 },
  { uf: 'AM', regiao: 'Norte', rede: 'Publica', mediaGeral: 466.41, registros: 991 },
  { uf: 'SE', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 465.5, registros: 711 },
  { uf: 'AP', regiao: 'Norte', rede: 'Publica', mediaGeral: 465.46, registros: 260 },
  { uf: 'AC', regiao: 'Norte', rede: 'Publica', mediaGeral: 462.77, registros: 316 },
  { uf: 'MA', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 461.01, registros: 1681 },
  { uf: 'PI', regiao: 'Nordeste', rede: 'Publica', mediaGeral: 460.04, registros: 1576 },
  { uf: 'TO', regiao: 'Norte', rede: 'Publica', mediaGeral: 459.98, registros: 927 },
];

export const regionNetworkScoreAverages: RegionNetworkScoreAverage[] = [
  { regiao: 'Norte', rede: 'Publica', mediaGeral: 470.04, registros: 4955 },
  { regiao: 'Norte', rede: 'Privada', mediaGeral: 548.2, registros: 1772 },
  { regiao: 'Nordeste', rede: 'Publica', mediaGeral: 471.41, registros: 15895 },
  { regiao: 'Nordeste', rede: 'Privada', mediaGeral: 551.06, registros: 9014 },
  { regiao: 'Centro-oeste', rede: 'Publica', mediaGeral: 483.55, registros: 5740 },
  { regiao: 'Centro-oeste', rede: 'Privada', mediaGeral: 564.07, registros: 3012 },
  { regiao: 'Sudeste', rede: 'Publica', mediaGeral: 502.52, registros: 26341 },
  { regiao: 'Sudeste', rede: 'Privada', mediaGeral: 583.07, registros: 19739 },
  { regiao: 'Sul', rede: 'Publica', mediaGeral: 502.51, registros: 12881 },
  { regiao: 'Sul', rede: 'Privada', mediaGeral: 575.11, registros: 4958 },
];

export const federalPrivateUrbanScores: FederalPrivateUrbanScore[] = [
  { area: 'Natureza', federalUrbana: 550.15, privadaUrbana: 537.45 },
  { area: 'Humanas', federalUrbana: 596.57, privadaUrbana: 577.52 },
  { area: 'Linguagens', federalUrbana: 563.13, privadaUrbana: 552.85 },
  { area: 'Matematica', federalUrbana: 597.24, privadaUrbana: 577.07 },
  { area: 'Redacao', federalUrbana: 632.3, privadaUrbana: 614.36 },
];

export const regionalFederalPrivateUrbanScores: RegionalFederalPrivateUrbanScore[] = [
  { regiao: 'Norte', area: 'Natureza', federalUrbana: 510.2, privadaUrbana: 516.17 },
  { regiao: 'Norte', area: 'Humanas', federalUrbana: 563.41, privadaUrbana: 561.35 },
  { regiao: 'Norte', area: 'Linguagens', federalUrbana: 530.04, privadaUrbana: 533.64 },
  { regiao: 'Norte', area: 'Matematica', federalUrbana: 529.46, privadaUrbana: 534.38 },
  { regiao: 'Norte', area: 'Redacao', federalUrbana: 592.03, privadaUrbana: 606.33 },
  { regiao: 'Nordeste', area: 'Natureza', federalUrbana: 527.85, privadaUrbana: 515.27 },
  { regiao: 'Nordeste', area: 'Humanas', federalUrbana: 580.78, privadaUrbana: 559.5 },
  { regiao: 'Nordeste', area: 'Linguagens', federalUrbana: 547.36, privadaUrbana: 534.17 },
  { regiao: 'Nordeste', area: 'Matematica', federalUrbana: 562.11, privadaUrbana: 542.18 },
  { regiao: 'Nordeste', area: 'Redacao', federalUrbana: 620.26, privadaUrbana: 605.19 },
  { regiao: 'Centro-oeste', area: 'Natureza', federalUrbana: 546.43, privadaUrbana: 532.75 },
  { regiao: 'Centro-oeste', area: 'Humanas', federalUrbana: 598.23, privadaUrbana: 571.86 },
  { regiao: 'Centro-oeste', area: 'Linguagens', federalUrbana: 561.62, privadaUrbana: 545.97 },
  { regiao: 'Centro-oeste', area: 'Matematica', federalUrbana: 581.07, privadaUrbana: 564.88 },
  { regiao: 'Centro-oeste', area: 'Redacao', federalUrbana: 628.32, privadaUrbana: 608.18 },
  { regiao: 'Sudeste', area: 'Natureza', federalUrbana: 584.61, privadaUrbana: 548.42 },
  { regiao: 'Sudeste', area: 'Humanas', federalUrbana: 621.95, privadaUrbana: 587.19 },
  { regiao: 'Sudeste', area: 'Linguagens', federalUrbana: 587.82, privadaUrbana: 563.03 },
  { regiao: 'Sudeste', area: 'Matematica', federalUrbana: 653.83, privadaUrbana: 595.73 },
  { regiao: 'Sudeste', area: 'Redacao', federalUrbana: 667.23, privadaUrbana: 622.26 },
  { regiao: 'Sul', area: 'Natureza', federalUrbana: 563.16, privadaUrbana: 544.16 },
  { regiao: 'Sul', area: 'Humanas', federalUrbana: 606.04, privadaUrbana: 580.7 },
  { regiao: 'Sul', area: 'Linguagens', federalUrbana: 574.91, privadaUrbana: 557.06 },
  { regiao: 'Sul', area: 'Matematica', federalUrbana: 621.34, privadaUrbana: 588.16 },
  { regiao: 'Sul', area: 'Redacao', federalUrbana: 625.37, privadaUrbana: 606.07 },
];

export const urbanRuralRegionScores: UrbanRuralRegionScore[] = [
  { regiao: 'Norte', urbana: 468.56, rural: 445.67, registrosUrbanos: 4448, registrosRurais: 309 },
  { regiao: 'Nordeste', urbana: 469.03, rural: 452.08, registrosUrbanos: 14397, registrosRurais: 720 },
  { regiao: 'Centro-oeste', urbana: 482.14, rural: 464.28, registrosUrbanos: 5305, registrosRurais: 269 },
  { regiao: 'Sudeste', urbana: 500.49, rural: 483.19, registrosUrbanos: 24290, registrosRurais: 944 },
  { regiao: 'Sul', urbana: 501.31, rural: 488.59, registrosUrbanos: 11761, registrosRurais: 767 },
];

export const correlationRows: { pair: string; value: number }[] = [
  { pair: 'CN x LP', value: 0.9 },
  { pair: 'CN x MT', value: 0.88 },
  { pair: 'LP x MT', value: 0.85 },
  { pair: 'CN x CH', value: 0.84 },
  { pair: 'CH x LP', value: 0.85 },
  { pair: 'CN x Redacao', value: 0.74 },
  { pair: 'CH x Redacao', value: 0.64 },
];

export const correlationMatrix: ({ area: string } & Record<SubjectKey, number>)[] = [
  { area: 'Natureza', cn: 1, ch: 0.84, lp: 0.9, mt: 0.88, redacao: 0.74 },
  { area: 'Humanas', cn: 0.84, ch: 1, lp: 0.85, mt: 0.73, redacao: 0.64 },
  { area: 'Linguagens', cn: 0.9, ch: 0.85, lp: 1, mt: 0.85, redacao: 0.72 },
  { area: 'Matematica', cn: 0.88, ch: 0.73, lp: 0.85, mt: 1, redacao: 0.7 },
  { area: 'Redacao', cn: 0.74, ch: 0.64, lp: 0.72, mt: 0.7, redacao: 1 },
];

export const mapPoints: MapPoint[] = [
  { id: 'brasil', label: 'Brasil', detail: 'Base nacional dos microdados ENEM por escola (2009-2015)', longitude: -53.2, latitude: -10.8, value: 104687, tone: 'primary' },
];

export const subjectLabels: Record<SubjectKey, string> = {
  cn: 'Natureza',
  ch: 'Humanas',
  lp: 'Linguagens',
  mt: 'Matematica',
  redacao: 'Redacao',
};

export const totalRecords = networkCounts.reduce((sum, item) => sum + item.registros, 0);
export const averagePublicPrivateGap = networkScores.reduce((sum, item) => sum + (item.privada - item.publica), 0) / networkScores.length;
